FROM python:3.12-slim

WORKDIR /app

RUN pip install poetry

COPY pyproject.toml poetry.lock ./

RUN poetry config virtualenvs.create false

RUN poetry install --no-interaction --no-ansi

COPY . .

EXPOSE 8000

CMD ["/bin/sh", "-c", "poetry run celery -A app.celery_client worker -P solo -l info & poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000"]