"""added ai insights and podcast features

Revision ID: 37be0a80c8f2
Revises: 107703e05e34
Create Date: 2026-06-12 22:17:33.234515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '37be0a80c8f2'
down_revision: Union[str, Sequence[str], None] = '107703e05e34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('books', sa.Column('key_takeaways', sa.JSON(), nullable=True))
    op.add_column('books', sa.Column('podcast_url_en', sa.String(), nullable=True))
    op.add_column('books', sa.Column('podcast_url_hi', sa.String(), nullable=True))
    op.add_column('books', sa.Column('podcast_generated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'podcast_generated_at')
    op.drop_column('books', 'podcast_url_hi')
    op.drop_column('books', 'podcast_url_en')
    op.drop_column('books', 'key_takeaways')
    op.drop_column('books', 'summary')
    # ### end Alembic commands ###
