"""add review unique constraint

Revision ID: 80fd9a110884
Revises: 9af4ace61779
Create Date: 2026-05-30 04:38:19.904262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '80fd9a110884'
down_revision: Union[str, Sequence[str], None] = '9af4ace61779'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_user_book_review', 'reviews', ['user_id', 'book_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_book_review', 'reviews', type_='unique')
    # ### end Alembic commands ###
