"""add file metadata to books

Revision ID: a59029e5c8b5
Revises: 80fd9a110884
Create Date: 2026-06-04 18:33:03.150569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'a59029e5c8b5'
down_revision: Union[str, Sequence[str], None] = '80fd9a110884'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('file_id', sa.String(), nullable=True))
    op.add_column('books', sa.Column('file_name', sa.String(), nullable=True))
    op.add_column('books', sa.Column('file_size', sa.BigInteger(), nullable=True))
    op.add_column('books', sa.Column('mime_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'mime_type')
    op.drop_column('books', 'file_size')
    op.drop_column('books', 'file_name')
    op.drop_column('books', 'file_id')
    # ### end Alembic commands ###
