"""Added Relatioship b/wUser and Book 

Revision ID: fa65eb0de5aa
Revises: 60625572357e
Create Date: 2026-05-29 21:57:04.170246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'fa65eb0de5aa'
down_revision: Union[str, Sequence[str], None] = '60625572357e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('owner_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'books', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'owner_id')
    # ### end Alembic commands ###
